stages:
- pre-build
- build
- test
- deploy

build-docker:
  stage: pre-build     
  script:
  - docker build -t minha-imagem .

build-project:
  services:
  - docker:dind
  - mysql:5.7
  variables: 
    MYSQL_USER: devops_dev
    MYSQL_PASSWORD: mestre123
    MYSQL_DATABASE: todo_dev
    MYSQL_ROOT_PASSWORD: mestre123

    DB_NAME: 'todo_dev'
    DB_USER: 'devops_dev'
    DB_PASSWORD: 'mestre123'
    DB_PORT: '3306'
    SECRET_KEY: 'r*5ltfzw-61ksdm41fuul8+hxs$86yo9%k1%k=(!@=-wv4qtyv'

  stage: build
  dependencies:
  - build-docker
  script:
  - echo "Ola"
  - python manage.py makemigrations
  - python manage.py migrate
