image: docker:stable

stages:
- pre-build
- build
- test
- deploy

build-docker:
    services:
    - docker:dind

    before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    stage: pre-build
    script: 
    - docker build - t minha-imagem .
    - docker tag minha-imagem kwws/minha-imagem:latest
    - docker push kwws/minha-imagem:latest

build-project:
    image: kwws/minha-imagem:latest
    services:
    - docker:dind
    - mysql:5.7
    variables:
        MYSQL_USER: devops_dev
        MYSQL_PASSWORD: mestre123
        MYSQL_DATABASE: todo_dev
        MYSQL_ROOT_PASSWORD: senha

        DB_NAME: 'todo_dev'
        DB USER: 'devops_dev'
        DB_PASSWORD: 'mestre123'
        DB_PORT: '3306'
        DB_HOST: 'mysql'
        SECRET_KEY: 'r*5ltfzw-61ksdm41fuul8+hxs$86yo9%k1%k=(!@=-wv4qtyv'

    stage: build
    image:kwws/minha-imagem:latest
    tags:
    - executor-tarefas
    dependencies:
    - build-docker
    script:
    - python manage.py makemigrations
    - python manage.py migrate
